### ISSUE TITLE
Dropping packets with Merlin

### ISSUE THREAD

**Issue by rodrigosoares** [merlin-lang/merlin#3]
Hi. Since the end of the last year I am using Merlin as part of my research application. Recently I was looking through the parser code and I did not find anything related to dropping packets that match predicates. Is even possible to drop packets with Merlin? If its not, is there a plan to implement it in the future? Maybe something like `tcpDstPort = 80 -> drop;`.

Regards.

**Comment by robertsoule-barefoot** [comment]
Hi Rodrigo, 

Merlin does not currently support a drop action. I'm afraid that we don't have any plans to implement it currently.

-Robert

**Comment by rodrigosoares** [comment]
OK, thanks for the answer!
